name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          rsync -avz --delete --exclude='.git' --exclude='.github' ./ $SSH_USER@$SSH_HOST:/var/www/portfolio/portfolio-front/

      - name: Rebuild Docker containers
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_USERNAME }}
        run: |
          ssh $SSH_USER@$SSH_HOST "cd /var/www/portfolio && \
          (docker compose down --volumes --remove-orphans || true) && \
          docker compose up --build -d"
